language: ruby
rvm:
  - 1.9.3
before_script: ./fix_future_test.sh
script: "rake test"
#addons:
#  code_climate:
#    repo_token: d878083b6a2d4f98bfe974506e9b214c5604551afc9ba1736ea9612b945496fd
env:
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.6.2
branches:
  only:
    - 0.0.4
    - 0.0.5
    - master
notifications:
  email: false
gemfile: Gemfile
